"""Datastore resource package."""

from celerity.resources.datastore.errors import (
    ConditionalCheckFailedError,
    DatastoreError,
)
from celerity.resources.datastore.params import (
    DEFAULT_DATASTORE_TOKEN,
    DatastoreParam,
    DatastoreResource,
    datastore_token,
    get_datastore,
)
from celerity.resources.datastore.types import (
    AndGroup,
    BatchGetItemsOptions,
    Condition,
    ConditionOperator,
    Datastore,
    DatastoreClient,
    DeleteItemOptions,
    DeleteOperation,
    GetItemOptions,
    ItemListing,
    KeyCondition,
    OrGroup,
    PutItemOptions,
    PutOperation,
    QueryParams,
    RangeCondition,
    RangeOperator,
    ScanParams,
)

__all__ = [
    "DEFAULT_DATASTORE_TOKEN",
    "AndGroup",
    "BatchGetItemsOptions",
    "Condition",
    "ConditionOperator",
    "ConditionalCheckFailedError",
    "Datastore",
    "DatastoreClient",
    "DatastoreError",
    "DatastoreParam",
    "DatastoreResource",
    "DeleteItemOptions",
    "DeleteOperation",
    "GetItemOptions",
    "ItemListing",
    "KeyCondition",
    "OrGroup",
    "PutItemOptions",
    "PutOperation",
    "QueryParams",
    "RangeCondition",
    "RangeOperator",
    "ScanParams",
    "datastore_token",
    "get_datastore",
]
