module.exports = {
  extends: ["@commitlint/config-conventional"],
  rules: {
    "type-enum": [
      2,
      "always",
      [
        "fix",
        "build",
        "revert",
        "wip",
        "feat",
        "chore",
        "ci",
        "docs",
        "style",
        "refactor",
        "perf",
        "test",
        "instr",
        "deps",
      ],
    ],
    "scope-enum": [
      2,
      "always",
      [
        "types",
        "common",
        "metadata",
        "decorators",
        "di",
        "bootstrap",
        "handlers",
        "layers",
        "errors",
        "functions",
        "testing",
        "cli",
        "serverless",
        "resources",
        "telemetry",
        "ci",
        "repo",
        "deps",
      ],
    ],
  },
};
