"""Shared resource infrastructure: resource links, platform, deploy target."""

from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any

logger = logging.getLogger("celerity.resource")

type Platform = str
"""One of ``"aws"``, ``"gcp"``, ``"azure"``, ``"local"``, ``"other"``."""

type RuntimeMode = str
"""One of ``"functions"`` or ``"runtime"``."""

RESOURCE_LINKS_FILENAME = "__celerity_resource_links__.json"
"""Name of the resource links file bundled alongside the handler code.

The Celerity CLI writes this file during the build step so the SDK can
discover the resource topology on cold start without relying on a large
environment variable payload.
"""


@dataclass(frozen=True)
class ResourceLink:
    """A single resource link from the blueprint."""

    type: str
    config_key: str


def _resolve_resource_links_path() -> Path:
    """Resolve where to read the resource links file from.

    The file sits next to the handler entry point by default; runtime
    platforms (e.g. local dev) may set ``CELERITY_RESOURCE_LINKS_PATH`` to
    point the SDK at a different location.
    """
    override = os.environ.get("CELERITY_RESOURCE_LINKS_PATH")
    if override:
        return Path(override)
    return Path.cwd() / RESOURCE_LINKS_FILENAME


def capture_resource_links() -> dict[str, ResourceLink]:
    """Load the resource link topology produced at build time by the Celerity CLI.

    The file contains JSON mapping resource names to their type and config key::

        {
            "orders-db": {"type": "datastore", "configKey": "ordersDb"},
            "app-cache": {"type": "cache", "configKey": "appCache"}
        }

    Returns:
        Dict mapping resource name to ``ResourceLink``.

    Raises:
        FileNotFoundError: if the resource links file is missing.
        ValueError: if the file cannot be parsed as JSON.
    """
    path = _resolve_resource_links_path()
    try:
        raw = path.read_text(encoding="utf-8")
    except FileNotFoundError as exc:
        msg = (
            f"resource links file not found at {path}: {exc}. "
            "this file is generated by `celerity build` / `celerity dev`."
        )
        raise FileNotFoundError(msg) from exc

    try:
        parsed: dict[str, Any] = json.loads(raw)
    except json.JSONDecodeError as exc:
        msg = f"resource links file at {path} is not valid JSON: {exc}"
        raise ValueError(msg) from exc

    links: dict[str, ResourceLink] = {}
    for name, value in parsed.items():
        if isinstance(value, dict) and "type" in value and "configKey" in value:
            links[name] = ResourceLink(
                type=value["type"],
                config_key=value["configKey"],
            )
    return links


def get_links_of_type(
    links: dict[str, ResourceLink],
    resource_type: str,
) -> dict[str, str]:
    """Filter links to a specific type.

    Returns:
        Dict mapping resource name to config key for the given type.
    """
    return {name: link.config_key for name, link in links.items() if link.type == resource_type}


def get_resource_types(links: dict[str, ResourceLink]) -> set[str]:
    """Get the set of distinct resource types present in links."""
    return {link.type for link in links.values()}


def detect_platform() -> Platform:
    """Read ``CELERITY_PLATFORM`` env var. Defaults to ``"other"``."""
    return os.environ.get("CELERITY_PLATFORM", "other")


def detect_runtime_mode() -> RuntimeMode:
    """Detect the runtime execution mode from environment.

    ``CELERITY_RUNTIME`` present → ``"runtime"`` (long-lived server),
    absent → ``"functions"`` (serverless/FaaS).
    """
    return "runtime" if os.environ.get("CELERITY_RUNTIME") else "functions"


def detect_cloud_deploy_target() -> str:
    """Read ``CELERITY_DEPLOY_TARGET`` env var.

    The deploy target identifies the cloud deployment configuration,
    e.g. ``"aws"``, ``"aws-serverless"``, ``"gcloud"``,
    ``"gcloud-serverless"``, ``"azure"``, ``"azure-serverless"``.

    Only used by the datastore factory in local environments to select
    the correct emulator (e.g. DynamoDB Local for AWS targets).
    Defaults to ``"aws"`` when not set.
    """
    return os.environ.get("CELERITY_DEPLOY_TARGET", "aws")


@dataclass(frozen=True, slots=True)
class AwsCredentials:
    """Explicit AWS credentials that override the default credential chain."""

    access_key_id: str
    secret_access_key: str


def capture_aws_credentials(
    access_key_env: str = "AWS_ACCESS_KEY_ID",
    secret_key_env: str = "AWS_SECRET_ACCESS_KEY",
) -> AwsCredentials | None:
    """Capture AWS credentials from environment variables.

    Args:
        access_key_env: Primary env var for the access key.
        secret_key_env: Primary env var for the secret key.

    Returns:
        ``AwsCredentials`` if both values are present, otherwise ``None``
        (falling back to the default credential chain).
    """
    access_key = os.environ.get(access_key_env) or os.environ.get("AWS_ACCESS_KEY_ID")
    secret_key = os.environ.get(secret_key_env) or os.environ.get("AWS_SECRET_ACCESS_KEY")
    if access_key and secret_key:
        return AwsCredentials(access_key_id=access_key, secret_access_key=secret_key)
    return None
